# Generated by Django 2.2.12 on 2022-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
